// native/organs/current-holder.js — a GROUND for the open-now fact "who holds this office?".
//
// The fact gate (fact-gate.js) found that a checkable present-tense fact has no ground to stand on: a web
// search snippet for "who is the president?" is the lead paragraph of a list article, which never names the
// current holder, so the mouth fell back on training memory. A fact is (jurisdiction, referent, relation, value)
// with a SCOPE and a GROUND; for an office the ground is DATED — Wikidata records officeholders (P1308 on the
// position item) with start (P580) and end (P582) qualifiers, so "current" is not a word list or a guess: it is
// the statement whose interval contains today. General across every office it records; nothing here names a role.
//
// The jurisdiction is not guessed: the position item is found by its exact label "<role> of <jurisdiction>"; no
// exact label, no ground (the caller ships the model's answer marked unchecked, as before).
//
// Cells (canon stays here): ●− INS·Ground Void·Cultivating — ground generated by a declared preflight, aimed at
// the resolved jurisdiction's own record; ⊨* EVA·Pattern — standing from a dated witness, kelsen's lex posterior.

const API = "https://www.wikidata.org/w/api.php";
const TIMEOUT_MS = 8000;
const norm = (s) => String(s ?? "").toLowerCase().replace(/\bthe\b/g, " ").replace(/\s+/g, " ").trim(); // same fold both sides: "the" is not part of an office's identity
const timeOf = (claim, prop) => claim?.qualifiers?.[prop]?.[0]?.datavalue?.value?.time ?? null;
const ms = (t) => (t ? Date.parse(String(t).replace(/^\+/, "").replace(/-00(?=-|T)/g, "-01")) : NaN);
const day = (t) => String(t ?? "").replace(/^\+/, "").slice(0, 10);

/** The statement whose [start, end) interval contains `now`; a rank-preferred one wins, then the latest start.
 * A statement with no start or no end is open on that side. Null when no statement covers today. */
export function pickCurrent(claims, now = new Date()) {
  const t = now.getTime();
  const covering = (claims ?? []).filter((c) => {
    if (c?.rank === "deprecated" || c?.mainsnak?.snaktype !== "value") return false;
    const s = ms(timeOf(c, "P580")), e = ms(timeOf(c, "P582"));
    return (Number.isNaN(s) || s <= t) && (Number.isNaN(e) || t < e);
  });
  if (!covering.length) return null;
  covering.sort((a, b) => ((b.rank === "preferred") - (a.rank === "preferred")) || ((ms(timeOf(b, "P580")) || 0) - (ms(timeOf(a, "P580")) || 0)));
  return covering[0];
}

async function api(fetchImpl, params, mayRetry = true) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetchImpl(`${API}?${new URLSearchParams({ format: "json", origin: "*", ...params })}`, { signal: ctrl.signal, headers: { "user-agent": "eoreader7-fact-gate/0.1 (local instrument; one lookup per explicit ask)" } });
    if (res.status === 429 && mayRetry) { await new Promise((r) => setTimeout(r, 1500)); return api(fetchImpl, params, false); } // one polite retry
    if (!res.ok) throw new Error(`wikidata ${res.status}`);
    return await res.json();
  } finally { clearTimeout(timer); }
}

/** currentHolder({ role, jurisdiction }) → { found, text, holder, start, end, ref, qid } | { found:false, why }. Never throws. */
export async function currentHolder({ role, jurisdiction, fetchImpl = globalThis.fetch, now = new Date() } = {}) {
  if (!role || !jurisdiction || typeof fetchImpl !== "function") return { found: false, why: "no role or jurisdiction" };
  try {
    const label = `${norm(role)} of ${norm(jurisdiction)}`;
    const found = await api(fetchImpl, { action: "wbsearchentities", search: `${role} of ${jurisdiction}`, language: "en", type: "item", limit: "8" });
    const item = (found?.search ?? []).find((x) => norm(x.label) === label && !/fiction|video game|character/i.test(x.description ?? ""));
    if (!item) return { found: false, why: `no position item labelled "${label}"` };
    const pos = await api(fetchImpl, { action: "wbgetentities", ids: item.id, props: "claims|labels", languages: "en|mul", languagefallback: "1" });
    const claims = pos?.entities?.[item.id]?.claims?.P1308 ?? [];
    const cur = pickCurrent(claims, now);
    if (!cur) return { found: false, why: "no dated officeholder statement covers today", qid: item.id };
    const holderQid = cur.mainsnak.datavalue.value.id;
    const who = await api(fetchImpl, { action: "wbgetentities", ids: holderQid, props: "labels", languages: "en|mul", languagefallback: "1" });
    const holder = who?.entities?.[holderQid]?.labels?.en?.value;
    if (!holder) return { found: false, why: "holder has no English label", qid: item.id };
    const start = day(timeOf(cur, "P580")), end = day(timeOf(cur, "P582"));
    const text = `Wikidata lists ${holder} as the current ${pos.entities[item.id].labels?.en?.value ?? item.label}${start ? `, since ${start}` : ""}${end ? `, term ending ${end}` : ""}.`;
    return { found: true, text, holder, start: start || null, end: end || null, qid: item.id, ref: `wikidata:${item.id}#P1308` };
  } catch (err) {
    return { found: false, why: String(err?.message ?? err) };
  }
}
