// parmenides.js — Parmenides, the archon of being: SAME vs OTHER.
//
// Handle: Parmenides of Elea. His doctrine has two ways, and so does this
// archon. The WAY OF TRUTH (aletheia): what a thing IS, and that what is,
// is — identity admitted by the equivalence organs themselves. The WAY OF
// SEEMING (doxa): how a thing appears — which the archon refuses outright.
// Two things are the SAME iff they participate in one form of being
// (surfaces folded, acts lemmatised, values generated by the received
// CLDR machinery, beings resolved by the referent index, kinds kept apart).
// A sameness resting only on appearance — string distance, a phonetic key,
// an embedding similarity — is not identity; it may nominate, never decide.
//
// This is the ENFORCEMENT archon of FOLD-CONSTITUTION II.7 (two records
// are the same iff they make the same difference — never by appearance,
// not even in principle) and P11 (identity through the referent index,
// never a string). "Being is one": a surface that resolves to a form IS
// that form; a form with a single member is a particular.
//
// The register lives in solon.js — the one authoritative list; this file
// does not restate it. Here: PARMENIDES (the Way — SAME vs OTHER), under
// kelsen (identity is a verdict, and every verdict is kelsen's).
//
// PURE. The equivalence organs are injected (the cast.js pattern): `fold`
// (diacritics + token folding), `sameAct` (morphology), `referentIndex`
// (beings), and `values` (the CLDR-backed form resolver for dates and
// numbers). Nothing here knows a language, a script, or a calendar.

export const FORMS = Object.freeze({
  SURFACE: "surface",     // folded token identity — "Rostopchín" ≡ "Rostopchin"
  ACT: "act",             // morphological identity — "withdraws" ≡ "withdrew"
  VALUE: "value",         // generated-form identity — "26 августа 1812" ≡ 1812-08-26
  BEING: "being",         // referent identity — Bezukhov the person, through evidence
  KIND: "kind",           // what a thing IS (P79) — a god "Mars" and a planet "Mars" are other
});

export const VERDICTS = Object.freeze({
  SAME: "same",
  OTHER: "other",
  REFUSED: "refused",
});

export function makeParmenides({ fold = null, sameAct = null, referentIndex = null, values = null, meaning = null } = {}) {
  // The Way of Truth: each organ admits a surface into a form when it can;
  // the first that admits BOTH sides decides. None admitting means the
  // sameness was never established, and the archon says refused rather
  // than guessing — appearance is the Way of Seeming, and is refused.
  const folded = (s) => (typeof fold === "function" ? fold(s) : null);

  const resolveBeing = (s) => {
    if (typeof referentIndex?.resolve === "function") {
      try {
        const r = referentIndex.resolve(s);
        return r && !r.gap ? r : null;
      } catch { return null; }
    }
    return null;
  };

  const resolveValue = (s) => {
    if (typeof values?.resolve === "function") {
      try {
        const v = values.resolve(s);
        return v && !v.gap && v.value ? v.value : null;
      } catch { return null; }
    }
    return null;
  };

  function formOf(surface) {
    // The form of being a surface participates in, or null if none admits it.
    const being = resolveBeing(surface);
    if (being) return { kind: FORMS.BEING, canon: being };
    const val = resolveValue(surface);
    if (val) return { kind: FORMS.VALUE, canon: val };
    if (sameAct) {
      try {
        const lemma = sameAct(surface);
        if (lemma) return { kind: FORMS.ACT, canon: lemma };
      } catch { /* fall through */ }
    }
    const f = folded(surface);
    if (f) return { kind: FORMS.SURFACE, canon: f };
    return null;
  }

  /**
   * The one question. `a` and `b` are surfaces (strings) or already-resolved
   * forms. Returns {verdict, via} where via names the form that admitted the
   * sameness — or the refusal. A sameness resting on no admitted form is
   * REFUSED, never SAME (II.7: identity by appearance is not identity).
   */
  function same(a, b) {
    if (a === b) return { verdict: VERDICTS.SAME, via: FORMS.SURFACE, detail: "identical surface" };
    const fa = formOf(a);
    const fb = formOf(b);
    if (!fa || !fb) return { verdict: VERDICTS.REFUSED, detail: fa ? "other side has no admitted form" : "this side has no admitted form", a, b };
    if (fa.kind !== fb.kind) return { verdict: VERDICTS.OTHER, via: FORMS.KIND, detail: `different form kinds: ${fa.kind} vs ${fb.kind}` };
    if (fa.canon === fb.canon) return { verdict: VERDICTS.SAME, via: fa.kind, canon: fa.canon };
    // The composed word-meaning prior (word-meaning.js: morphology + synsets
    // + values, language-declared and vendored): two surfaces that neither
    // resolve to the same being/value/act but the MEANING organ equates are
    // one form of meaning — the P74 synonymy walls, closed by a received
    // prior rather than a model. Absent, the surfaces differ.
    if (typeof meaning === "function") {
      try {
        const m = meaning(a, b);
        if (m?.same) return { verdict: VERDICTS.SAME, via: FORMS.SURFACE, meaningVia: m.via, detail: `same meaning (${m.via})` };
      } catch { /* fall through */ }
    }
    return { verdict: VERDICTS.OTHER, via: fa.kind, detail: `different ${fa.kind} forms` };
  }

  /**
   * KIND identity (P79): the same surface may instantiate different kinds —
   * a god "Mars" and a planet "Mars" are OTHER even though the string is
   * identical, because they participate in different forms of being.
   * `kindOf` is injected by the caller (kind-standing.js). Returns
   * {verdict, kind} or {verdict: "refused"} when no kind organ is injected.
   */
  function sameKind(a, b, kindOf = null) {
    if (typeof kindOf !== "function") return { verdict: VERDICTS.REFUSED, detail: "no kind organ injected (kind-standing.js, P79)" };
    const ka = kindOf(a);
    const kb = kindOf(b);
    if (ka && kb && ka !== kb) return { verdict: VERDICTS.OTHER, kind: [ka, kb] };
    if (ka && kb && ka === kb) return { verdict: VERDICTS.SAME, kind: ka };
    return { verdict: VERDICTS.REFUSED, detail: "kind unresolved on one side" };
  }

  return { same, formOf, sameKind, FORMS, VERDICTS };
}