export const NEW_TASKS = [
  {
    id: "boundary_walk", snake: "boundary_walk",
    spec: "Write a function boundary_walk that takes exactly one argument, a grid, which is a list of rows of integers where every row has the same length (at least 1), and returns a flat list of the cells on its outer edge, each cell listed once, starting at the top-left cell and going clockwise: along the top row left to right, down the last column, back along the bottom row right to left, then up the first column. A grid with a single row gives that row, a grid with a single column gives that column from top to bottom, and an empty grid (no rows) gives an empty list.",
    cases: [
      { args: [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], expect: [1, 2, 3, 6, 9, 8, 7, 4] },
      { args: [[]], expect: [] },
      { args: [[[5]]], expect: [5] },
      { args: [[[1, 2, 3, 4]]], expect: [1, 2, 3, 4] },
      { args: [[[1], [2], [3]]], expect: [1, 2, 3] },
      { args: [[[1, 2], [3, 4], [5, 6]]], expect: [1, 2, 4, 6, 5, 3] },
      { args: [[[1, 2, 3], [4, 5, 6]]], expect: [1, 2, 3, 6, 5, 4] },
      { args: [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]], expect: [1, 2, 3, 4, 8, 12, 11, 10, 9, 5] },
    ],
    ref: {
      javascript: "const __F__ = (grid) => { const r = grid.length; if (r === 0) return []; const c = grid[0].length; const o = []; for (let j = 0; j < c; j++) o.push(grid[0][j]); for (let i = 1; i < r; i++) o.push(grid[i][c - 1]); if (r > 1) for (let j = c - 2; j >= 0; j--) o.push(grid[r - 1][j]); if (c > 1) for (let i = r - 2; i >= 1; i--) o.push(grid[i][0]); return o; };",
      typescript: "const __F__ = (grid: number[][]): number[] => { const r = grid.length; if (r === 0) return []; const c = grid[0].length; const o: number[] = []; for (let j = 0; j < c; j++) o.push(grid[0][j]); for (let i = 1; i < r; i++) o.push(grid[i][c - 1]); if (r > 1) for (let j = c - 2; j >= 0; j--) o.push(grid[r - 1][j]); if (c > 1) for (let i = r - 2; i >= 1; i--) o.push(grid[i][0]); return o; };",
      python: "def __F__(grid):\n    r = len(grid)\n    if r == 0:\n        return []\n    c = len(grid[0])\n    out = list(grid[0])\n    for i in range(1, r):\n        out.append(grid[i][c - 1])\n    if r > 1:\n        for j in range(c - 2, -1, -1):\n            out.append(grid[r - 1][j])\n    if c > 1:\n        for i in range(r - 2, 0, -1):\n            out.append(grid[i][0])\n    return out",
      ruby: "def __F__(grid)\n  r = grid.length\n  return [] if r == 0\n  c = grid[0].length\n  out = grid[0].dup\n  (1...r).each { |i| out << grid[i][c - 1] }\n  if r > 1\n    (c - 2).downto(0) { |j| out << grid[r - 1][j] }\n  end\n  if c > 1\n    (r - 2).downto(1) { |i| out << grid[i][0] }\n  end\n  out\nend",
    },
  },
  {
    id: "larger_neighbours", snake: "larger_neighbours",
    spec: "Write a function larger_neighbours that takes exactly one argument, a grid, which is a list of rows of integers where every row has the same length (at least 1), and returns a grid of the same shape in which each cell holds how many of that cell's up, down, left and right neighbours (only those that exist) contain a strictly larger integer than the cell itself. Diagonal cells are not neighbours, equal values are not larger, and an empty grid (no rows) gives an empty list.",
    cases: [
      { args: [[[1, 2], [3, 4]]], expect: [[2, 1], [1, 0]] },
      { args: [[]], expect: [] },
      { args: [[[7]]], expect: [[0]] },
      { args: [[[1, 3, 1]]], expect: [[1, 0, 1]] },
      { args: [[[2], [2], [5]]], expect: [[0], [1], [0]] },
      { args: [[[5, 5], [5, 5]]], expect: [[0, 0], [0, 0]] },
      { args: [[[1, 2, 3], [4, 9, 6], [7, 8, 0]]], expect: [[2, 2, 1], [2, 0, 1], [1, 1, 2]] },
      { args: [[[3, 1, 4, 1], [5, 9, 2, 6]]], expect: [[1, 3, 0, 2], [1, 0, 3, 0]] },
    ],
    ref: {
      javascript: "const __F__ = (grid) => grid.map((row, i) => row.map((v, j) => [[-1, 0], [1, 0], [0, -1], [0, 1]].filter(([di, dj]) => { const a = i + di, b = j + dj; return a >= 0 && a < grid.length && b >= 0 && b < row.length && grid[a][b] > v; }).length));",
      typescript: "const __F__ = (grid: number[][]): number[][] => grid.map((row, i) => row.map((v, j) => [[-1, 0], [1, 0], [0, -1], [0, 1]].filter(([di, dj]) => { const a = i + di, b = j + dj; return a >= 0 && a < grid.length && b >= 0 && b < row.length && grid[a][b] > v; }).length));",
      python: "def __F__(grid):\n    out = []\n    for i, row in enumerate(grid):\n        line = []\n        for j, v in enumerate(row):\n            n = 0\n            for di, dj in ((-1, 0), (1, 0), (0, -1), (0, 1)):\n                a, b = i + di, j + dj\n                if 0 <= a < len(grid) and 0 <= b < len(row) and grid[a][b] > v:\n                    n += 1\n            line.append(n)\n        out.append(line)\n    return out",
      ruby: "def __F__(grid)\n  grid.each_with_index.map do |row, i|\n    row.each_with_index.map do |v, j|\n      [[-1, 0], [1, 0], [0, -1], [0, 1]].count do |di, dj|\n        a = i + di\n        b = j + dj\n        a >= 0 && a < grid.length && b >= 0 && b < row.length && grid[a][b] > v\n      end\n    end\n  end\nend",
    },
  },
  {
    id: "saddle_values", snake: "saddle_values",
    spec: "Write a function saddle_values that takes exactly one argument, a grid, which is a list of rows of integers where every row has the same length (at least 1), and returns a flat list of the value of every cell that is less than or equal to every value in its own row and also greater than or equal to every value in its own column. The values are listed in row-major order (top row first, each row left to right), a value that qualifies in several cells is listed once per cell, and if no cell qualifies or the grid is empty (no rows) the result is an empty list.",
    cases: [
      { args: [[[3, 1, 4], [2, 0, 5], [9, 8, 6]]], expect: [6] },
      { args: [[]], expect: [] },
      { args: [[[7]]], expect: [7] },
      { args: [[[2, 2], [2, 2]]], expect: [2, 2, 2, 2] },
      { args: [[[1, 2, 3]]], expect: [1] },
      { args: [[[1], [2], [3]]], expect: [3] },
      { args: [[[1, 2], [2, 1]]], expect: [] },
      { args: [[[4, 5, 6], [1, 2, 3]]], expect: [4] },
    ],
    ref: {
      javascript: "const __F__ = (grid) => { const out = []; grid.forEach((row, i) => row.forEach((v, j) => { if (v <= Math.min(...row) && v >= Math.max(...grid.map((r) => r[j]))) out.push(v); })); return out; };",
      typescript: "const __F__ = (grid: number[][]): number[] => { const out: number[] = []; grid.forEach((row, i) => row.forEach((v, j) => { if (v <= Math.min(...row) && v >= Math.max(...grid.map((r) => r[j]))) out.push(v); })); return out; };",
      python: "def __F__(grid):\n    out = []\n    for i, row in enumerate(grid):\n        for j, v in enumerate(row):\n            if v <= min(row) and v >= max(r[j] for r in grid):\n                out.append(v)\n    return out",
      ruby: "def __F__(grid)\n  out = []\n  grid.each_with_index do |row, i|\n    row.each_with_index do |v, j|\n      out << v if v <= row.min && v >= grid.map { |r| r[j] }.max\n    end\n  end\n  out\nend",
    },
  },
  {
    id: "diagonal_sums", snake: "diagonal_sums",
    spec: "Write a function diagonal_sums that takes exactly one argument, a grid, which is a list of rows of integers where every row has the same length (at least 1), and returns a list with the sum of each diagonal that runs from upper left to lower right. The diagonals are ordered by where they start: first the diagonal that is only the bottom-left cell, then moving up the left edge, then moving right along the top edge, ending with the diagonal that is only the top-right cell. A grid with r rows and c columns therefore gives r+c-1 sums, and an empty grid (no rows) gives an empty list.",
    cases: [
      { args: [[[1, 2], [3, 4]]], expect: [3, 5, 2] },
      { args: [[]], expect: [] },
      { args: [[[5]]], expect: [5] },
      { args: [[[1, 2, 3]]], expect: [1, 2, 3] },
      { args: [[[1], [2], [3]]], expect: [3, 2, 1] },
      { args: [[[1, 2, 3], [4, 5, 6]]], expect: [4, 6, 8, 3] },
      { args: [[[1, 2], [3, 4], [5, 6]]], expect: [5, 9, 5, 2] },
      { args: [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], expect: [7, 12, 15, 8, 3] },
    ],
    ref: {
      javascript: "const __F__ = (grid) => { const r = grid.length; if (r === 0) return []; const c = grid[0].length; const out = new Array(r + c - 1).fill(0); grid.forEach((row, i) => row.forEach((v, j) => { out[j - i + r - 1] += v; })); return out; };",
      typescript: "const __F__ = (grid: number[][]): number[] => { const r = grid.length; if (r === 0) return []; const c = grid[0].length; const out: number[] = new Array(r + c - 1).fill(0); grid.forEach((row, i) => row.forEach((v, j) => { out[j - i + r - 1] += v; })); return out; };",
      python: "def __F__(grid):\n    r = len(grid)\n    if r == 0:\n        return []\n    c = len(grid[0])\n    out = [0] * (r + c - 1)\n    for i in range(r):\n        for j in range(c):\n            out[j - i + r - 1] += grid[i][j]\n    return out",
      ruby: "def __F__(grid)\n  r = grid.length\n  return [] if r == 0\n  c = grid[0].length\n  out = Array.new(r + c - 1, 0)\n  grid.each_with_index do |row, i|\n    row.each_with_index { |v, j| out[j - i + r - 1] += v }\n  end\n  out\nend",
    },
  },
];
