// 4 new SMALL TEXT PARSING tasks (middle difficulty).
export const NEW_TASKS = [
  {
    id: "kv_lookup", snake: "kv_lookup",
    spec: "Write a function kv_lookup that takes a string text and a string key. The text is a list of pairs separated by semicolons, and each pair is a name and a value separated by the first equals sign, like \"a=1;b=2\", so a name never contains an equals sign but a value may (and may be empty). Return the value of the first pair whose name equals key exactly (case-sensitive, no trimming of spaces), so a key containing an equals sign matches nothing. Pieces with no equals sign, including empty pieces caused by repeated or trailing semicolons, are skipped, and if no pair matches return an empty string.",
    cases: [
      { args: ["a=1;b=2", "b"], expect: "2" },
      { args: ["name=Ann;age=31", "name"], expect: "Ann" },
      { args: ["", "x"], expect: "" },
      { args: ["a=1;;b=2;", "b"], expect: "2" },
      { args: ["a=1;b=2", "c"], expect: "" },
      { args: ["a=1;a=9", "a"], expect: "1" },
      { args: ["eq=x=y;z=1", "eq"], expect: "x=y" },
      { args: ["junk;k=v", "junk"], expect: "" },
      { args: ["A=1", "a"], expect: "" },
    ],
    ref: {
      javascript: "const __F__ = (text, key) => {\n  for (const p of text.split(';')) {\n    const i = p.indexOf('=');\n    if (i >= 0 && p.slice(0, i) === key) return p.slice(i + 1);\n  }\n  return '';\n};",
      typescript: "const __F__ = (text: string, key: string): string => {\n  for (const p of text.split(';')) {\n    const i: number = p.indexOf('=');\n    if (i >= 0 && p.slice(0, i) === key) return p.slice(i + 1);\n  }\n  return '';\n};",
      python: "def __F__(text, key):\n    for p in text.split(';'):\n        i = p.find('=')\n        if i >= 0 and p[:i] == key:\n            return p[i + 1:]\n    return ''",
      ruby: "def __F__(text, key)\n  text.split(';', -1).each do |p|\n    i = p.index('=')\n    return p[(i + 1)..] if i && p[0, i] == key\n  end\n  ''\nend",
    },
  },
  {
    id: "minutes_between", snake: "minutes_between",
    spec: "Write a function minutes_between that takes two strings start and end, each a time of day written as HH:MM with exactly two digits for the hour (00 to 23), a colon, and exactly two digits for the minute (00 to 59). Return the number of minutes from start until end; if end is earlier than start it is the next day, so the answer wraps past midnight, and equal times give 0. If either string is not in that exact format, return -1.",
    cases: [
      { args: ["09:15", "10:00"], expect: 45 },
      { args: ["00:00", "23:59"], expect: 1439 },
      { args: ["22:30", "01:10"], expect: 160 },
      { args: ["12:00", "12:00"], expect: 0 },
      { args: ["9:15", "10:00"], expect: -1 },
      { args: ["24:00", "01:00"], expect: -1 },
      { args: ["10:60", "11:00"], expect: -1 },
      { args: ["", "10:00"], expect: -1 },
      { args: ["10:00", "ab:cd"], expect: -1 },
    ],
    ref: {
      javascript: "const __F__ = (start, end) => {\n  const re = /^([01]\\d|2[0-3]):([0-5]\\d)$/;\n  const a = re.exec(start), b = re.exec(end);\n  if (!a || !b) return -1;\n  const m = (x) => Number(x[1]) * 60 + Number(x[2]);\n  return (((m(b) - m(a)) % 1440) + 1440) % 1440;\n};",
      typescript: "const __F__ = (start: string, end: string): number => {\n  const re = /^([01]\\d|2[0-3]):([0-5]\\d)$/;\n  const a = re.exec(start), b = re.exec(end);\n  if (!a || !b) return -1;\n  const m = (x: RegExpExecArray): number => Number(x[1]) * 60 + Number(x[2]);\n  return (((m(b) - m(a)) % 1440) + 1440) % 1440;\n};",
      python: "import re\n\ndef __F__(start, end):\n    pat = re.compile(r'([01][0-9]|2[0-3]):([0-5][0-9])')\n    a = pat.fullmatch(start)\n    b = pat.fullmatch(end)\n    if not a or not b:\n        return -1\n    m = lambda x: int(x.group(1)) * 60 + int(x.group(2))\n    return (m(b) - m(a)) % 1440",
      ruby: "def __F__(start, finish)\n  re = /\\A([01][0-9]|2[0-3]):([0-5][0-9])\\z/\n  a = re.match(start)\n  b = re.match(finish)\n  return -1 unless a && b\n  m = ->(x) { x[1].to_i * 60 + x[2].to_i }\n  (m.(b) - m.(a)) % 1440\nend",
    },
  },
  {
    id: "sum_embedded_numbers", snake: "sum_embedded_numbers",
    spec: "Write a function sum_embedded_numbers that takes a string and returns the sum of all the whole numbers written inside it, where a number is any maximal run of consecutive digits 0-9 read as a non-negative decimal integer (leading zeros allowed), so \"a1b22\" contains 1 and 22. Minus signs and decimal points are not part of a number, so \"3.5\" contains the numbers 3 and 5. A string with no digits, including an empty string, gives 0, and you may assume the total is below one billion.",
    cases: [
      { args: ["I have 3 apples and 12 pears"], expect: 15 },
      { args: ["no digits here"], expect: 0 },
      { args: [""], expect: 0 },
      { args: ["007 and 0"], expect: 7 },
      { args: ["a1b22c333"], expect: 356 },
      { args: ["-5 and 3.5"], expect: 13 },
      { args: ["1234567"], expect: 1234567 },
    ],
    ref: {
      javascript: "const __F__ = (s) => (s.match(/[0-9]+/g) || []).reduce((a, d) => a + parseInt(d, 10), 0);",
      typescript: "const __F__ = (s: string): number => (s.match(/[0-9]+/g) || []).reduce((a: number, d: string) => a + parseInt(d, 10), 0);",
      python: "import re\n\ndef __F__(s):\n    return sum(int(d) for d in re.findall(r'[0-9]+', s))",
      ruby: "def __F__(s)\n  s.scan(/[0-9]+/).sum(&:to_i)\nend",
    },
  },
  {
    id: "count_filled_fields", snake: "count_filled_fields",
    spec: "Write a function count_filled_fields that takes a string line and an integer n. Split line at every comma into fields (so \"a,,c\" has three fields and the empty string has one empty field), and remove spaces from both ends of each field. If the number of fields is not exactly n, return -1; otherwise return how many of the fields are not empty after that trimming.",
    cases: [
      { args: ["a,b,c", 3], expect: 3 },
      { args: ["a,,c", 3], expect: 2 },
      { args: ["a,b", 3], expect: -1 },
      { args: ["", 1], expect: 0 },
      { args: ["a,b,", 3], expect: 2 },
      { args: [" , x ,y", 3], expect: 2 },
      { args: [",,", 3], expect: 0 },
      { args: ["a,b,c,d", 3], expect: -1 },
      { args: ["a", 1], expect: 1 },
    ],
    ref: {
      javascript: "const __F__ = (line, n) => {\n  const fields = line.split(',').map((f) => f.trim());\n  return fields.length !== n ? -1 : fields.filter((f) => f !== '').length;\n};",
      typescript: "const __F__ = (line: string, n: number): number => {\n  const fields: string[] = line.split(',').map((f: string) => f.trim());\n  return fields.length !== n ? -1 : fields.filter((f: string) => f !== '').length;\n};",
      python: "def __F__(line, n):\n    fields = [f.strip(' ') for f in line.split(',')]\n    if len(fields) != n:\n        return -1\n    return sum(1 for f in fields if f)",
      ruby: "def __F__(line, n)\n  fields = line.split(',', -1).map { |f| f.strip }\n  fields = [''] if fields.empty?\n  return -1 if fields.length != n\n  fields.count { |f| !f.empty? }\nend",
    },
  },
];
